mobs:register_mob("mobs:creeper", {
	type = "monster",
	hp_max = 10,
	collisionbox = {-0.2, 0, -0.2, 0.2, 1.4, 0.2},
	visual = "mesh",
	mesh = "mobs_mc_creeper.b3d",
	textures = {"mobs_mc_creeper.png"},
	visual_size = { x = 3, y = 3 },
	makes_footstep_sound = true,
	view_range = 15,
	walk_velocity = 1.3,
	randomsound= "creeper_random",
	run_velocity = 1.1,
	on_rightclick = nil,
	jump = 0,
	damage = 0,
	drops = {
		{name = "default:gunpowder",
		chance = 1,
		min = 1,
		max = 3,},
	},
	armor = 70,
	drawtype = "front",
	lava_damage = 15,
	light_damage = 0,
	attack_type = "kamicaze",
})

